spring.application.name=userservice

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#spring.datasource.url=jdbc:mysql://mysqldb:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka/

#jwt.secret=${JWT_SECRET}

# ????? ???? ?? ?????.
spring.profiles.active=default

# ?? ??? ???? localhost? ?????.
spring.config.import=optional:configserver:http://configservice:8888

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

app.rabbitmq.order-created.exchange=order.exchange
app.rabbitmq.order-created.routing-key=order.created
app.rabbitmq.order-created.history-queue=order.history.queue
app.rabbitmq.order-created.notification-queue=order.notification.queue
app.rabbitmq.order-created.logging-queue=order.logging.queue
app.rabbitmq.order-created.notification-retry-queue=order.notification.retry.queue
app.rabbitmq.order-created.notification-dlq=order.notification.dlq
app.rabbitmq.order-created.notification-retry-exchange=order.notification.retry.exchange
app.rabbitmq.order-created.notification-dlx=order.notification.dlx
app.rabbitmq.order-created.notification-retry-routing-key=order.notification.retry
app.rabbitmq.order-created.notification-dlq-routing-key=order.notification.dlq
app.rabbitmq.order-created.notification-retry-ttl=10000
app.rabbitmq.order-created.notification-max-retry-count=3
app.rabbitmq.order-compensation.routing-key=order.compensation.requested
