spring.application.name=configservice
server.port=8888



spring.cloud.config.server.git.uri=https://github.com/0hj1hyeon/my-msa-config-repo.git
spring.cloud.config.server.git.default-label=main


spring.cloud.config.server.git.username=0hj1hyeon
spring.profiles.include=secret

eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka/